name: Jekyll site CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Jekyll Actions
          uses: helaili/jekyll-action@2.3.1
    

